name: Verificação de Saúde do Código Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-health:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Altere caso use outra versão

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Instalar ferramentas de qualidade de código
      run: |
        pip install flake8 pytest

    - name: Checar qualidade com flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Executar testes (pytest)
      run: |
        if [ -d tests ]; then pytest tests; fi
